In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv("retail_store_inventory.csv")
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [4]:
df.tail()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
73095,2024-01-01,S005,P0016,Furniture,East,96,8,127,18.46,73.73,20,Snowy,0,72.45,Winter
73096,2024-01-01,S005,P0017,Toys,North,313,51,101,48.43,82.57,10,Cloudy,0,83.78,Autumn
73097,2024-01-01,S005,P0018,Clothing,West,278,36,151,39.65,11.11,10,Rainy,0,10.91,Winter
73098,2024-01-01,S005,P0019,Toys,East,374,264,21,270.52,53.14,20,Rainy,0,55.80,Spring
73099,2024-01-01,S005,P0020,Groceries,East,117,6,165,2.33,78.39,20,Rainy,1,79.52,Spring

In [5]:
df.shape

(73100, 15)

In [6]:
print("Column Names:")
print(df.columns.tolist())

Column Names:
['Date', 'Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Units Sold', 'Units Ordered', 'Demand Forecast', 'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion', 'Competitor Pricing', 'Seasonality']

In [7]:
df.columns = df.columns.str.strip().str.lower()
df.columns = df.columns.str.replace(" ","_")

In [8]:
df.columns

Index(['date', 'store_id', 'product_id', 'category', 'region',
       'inventory_level', 'units_sold', 'units_ordered', 'demand_forecast',
       'price', 'discount', 'weather_condition', 'holiday/promotion',
       'competitor_pricing', 'seasonality'],
      dtype='object')

In [9]:
df.describe(include="object")

,date,store_id,product_id,category,region,weather_condition,seasonality
count,73100,73100,73100,73100,73100,73100,73100
unique,731,5,20,5,4,4,4
top,2022-01-01,S001,P0001,Furniture,East,Sunny,Spring
freq,100,14620,3655,14699,18349,18290,18317

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                73100 non-null  object
 1   store_id            73100 non-null  object
 2   product_id          73100 non-null  object
 3   category            73100 non-null  object
 4   region              73100 non-null  object
 5   inventory_level     73100 non-null  int64
 6   units_sold          73100 non-null  int64
 7   units_ordered       73100 non-null  int64
 8   demand_forecast     73100 non-null  float64
 9   price               73100 non-null  float64
 10  discount            73100 non-null  int64
 11  weather_condition   73100 non-null  object
 12  holiday/promotion   73100 non-null  int64
 13  competitor_pricing  73100 non-null  float64
 14  seasonality         73100 non-null  object
dtypes: float64(3), int64(5), object(7)
memory usage: 8.4+ MB

In [11]:
missing_values = df.isnull().sum()

print(missing_values)

date                  0
store_id              0
product_id            0
category              0
region                0
inventory_level       0
units_sold            0
units_ordered         0
demand_forecast       0
price                 0
discount              0
weather_condition     0
holiday/promotion     0
competitor_pricing    0
seasonality           0
dtype: int64

In [12]:
# Duplicate Rows
duplicate_rows = df.duplicated().sum()

print("Number of Duplicate Rows:", duplicate_rows)

Number of Duplicate Rows: 0

In [13]:
# Unique Values
for column in df.columns:
    print(
        column,
        "→",
        df[column].nunique(),
        "unique values"
    )

date → 731 unique values
store_id → 5 unique values
product_id → 20 unique values
category → 5 unique values
region → 4 unique values
inventory_level → 451 unique values
units_sold → 498 unique values
units_ordered → 181 unique values
demand_forecast → 31608 unique values
price → 8999 unique values
discount → 5 unique values
weather_condition → 4 unique values
holiday/promotion → 2 unique values
competitor_pricing → 9751 unique values
seasonality → 4 unique values

In [14]:
df.dtypes

date                   object
store_id               object
product_id             object
category               object
region                 object
inventory_level         int64
units_sold              int64
units_ordered           int64
demand_forecast       float64
price                 float64
discount                int64
weather_condition      object
holiday/promotion       int64
competitor_pricing    float64
seasonality            object
dtype: object

In [15]:
df["date"] = pd.to_datetime(df["date"], errors="coerce")

In [16]:
print(df["date"].dtype)

datetime64[ns]

In [17]:
# Date Range 
print("Starting Date: ",df["date"].min())
print("Ending Date: ",df["date"].max())

Starting Date:  2022-01-01 00:00:00
Ending Date:  2024-01-01 00:00:00

In [18]:
invalid_dates = df["date"].isnull().sum()

print("Invalid Dates:", invalid_dates)

Invalid Dates: 0

In [19]:
# numericals columns
numeric_columns = df.select_dtypes(
    include=np.number
).columns

print("Numerical Columns:")
print(numeric_columns.tolist())

Numerical Columns:
['inventory_level', 'units_sold', 'units_ordered', 'demand_forecast', 'price', 'discount', 'holiday/promotion', 'competitor_pricing']

In [20]:
# Check Negative Values
for column in numeric_columns:
    negative_values = (df[column] < 0).sum()

    print(
        column,
        "→",
        negative_values,
        "negative values"
    )

inventory_level → 0 negative values
units_sold → 0 negative values
units_ordered → 0 negative values
demand_forecast → 673 negative values
price → 0 negative values
discount → 0 negative values
holiday/promotion → 0 negative values
competitor_pricing → 0 negative values

In [21]:
median_demand = df["demand_forecast"].median()

print("Median Demand Forecast:", median_demand)

Median Demand Forecast: 113.015

In [22]:
df["demand_forecast"] = df["demand_forecast"].apply(
    lambda x: median_demand if x < 0 else x
)

In [23]:
print(
    "Negative Demand Forecast values:",
    (df["demand_forecast"] < 0).sum()
)

Negative Demand Forecast values: 0

In [24]:
negative_count = (df["demand_forecast"] < 0).sum()

print("Negative values replaced:", negative_count)
print("Replacement value (Median):", median_demand)

Negative values replaced: 0
Replacement value (Median): 113.015

In [25]:
categorical_columns = df.select_dtypes(
    include="object"
).columns

for column in categorical_columns:
    print("\n", column)
    print(df[column].unique()[:20])

 store_id
['S001' 'S002' 'S003' 'S004' 'S005']

 product_id
['P0001' 'P0002' 'P0003' 'P0004' 'P0005' 'P0006' 'P0007' 'P0008' 'P0009'
 'P0010' 'P0011' 'P0012' 'P0013' 'P0014' 'P0015' 'P0016' 'P0017' 'P0018'
 'P0019' 'P0020']

 category
['Groceries' 'Toys' 'Electronics' 'Furniture' 'Clothing']

 region
['North' 'South' 'West' 'East']

 weather_condition
['Rainy' 'Sunny' 'Cloudy' 'Snowy']

 seasonality
['Autumn' 'Summer' 'Winter' 'Spring']

In [26]:
data_quality = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str).values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique().values
})

data_quality

                Column       Data Type  Missing Values  Unique Values
0                 date  datetime64[ns]               0            731
1             store_id          object               0              5
2           product_id          object               0             20
3             category          object               0              5
4               region          object               0              4
5      inventory_level           int64               0            451
6           units_sold           int64               0            498
7        units_ordered           int64               0            181
8      demand_forecast         float64               0          31156
9                price         float64               0           8999
10            discount           int64               0              5
11   weather_condition          object               0              4
12   holiday/promotion           int64               0              2
13  competitor_pricing         float64               0           9751
14         seasonality          object               0              4

In [27]:
for column in numeric_columns:
    negative_values = (df[column] < 0).sum()
    print(column, "→", negative_values, "negative values")

inventory_level → 0 negative values
units_sold → 0 negative values
units_ordered → 0 negative values
demand_forecast → 0 negative values
price → 0 negative values
discount → 0 negative values
holiday/promotion → 0 negative values
competitor_pricing → 0 negative values

In [28]:
# Data Visualization 
total_sales = df["sales"].sum()

print("Total Sales:", round(total_sales, 2))

KeyError: 'sales'